### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by brendanrichards73** [SchoolOfCode/final-project-app-hip-hip#15]
As a user I would like to select how many teams will be playing and then register for a team and begin playing the game.

- [ ] Welcome animation (branding) to the game.
- [ ] Scroll down for basic instructions of what the game is. 
- [x] Button to enter a Room.
- [x] Display code to join a team
- [x] Button to join a team.
- [x] Enter a name when joining a team.
